blank_issues_enabled: true

# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Merci d'avoir signalÃ© une amÃ©lioration possible du site ! Pense Ã  regarder notre [code of conduct](https://github.com/women-on-rails/ressources/blob/master/CODE_OF_CONDUCT.md) et le [guide pour contribuer](https://github.com/women-on-rails/ressources/blob/master/CONTRIBUTING.md)

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Merci d'avoir proposÃ© une amÃ©lioration du site ! ğŸ™ Pense Ã  regarder notre [code of conduct](https://github.com/women-on-rails/ressources/blob/master/CODE_OF_CONDUCT.md) et le [guide pour contribuer](https://github.com/women-on-rails/ressources/blob/master/CONTRIBUTING.md)

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  FÃ©licitations pour le merge de ta premiÃ¨re Pull Request !  ğŸ‰ ğŸ‰ ğŸ‰

# It is recommended to include as many gifs and emojis as possible!
